### ISSUE TITLE
Optimise error messages

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/passport-ghost#5]
When starting Ghost and passport-ghost can't connect to Patronus, i am getting this:

```
kirrg001@DESKTOP-PETFQIA MINGW64 ~/Desktop/dev/ghost (master)
$ node index.js
[2016-10-27 10:07:14] ERROR

The request could not be understood.
level:normal

BadRequestError: The request could not be understood.
    at new BadRequestError (C:\Users\kirrg001\Desktop\dev\ghost\node_modules\passport-ghost\node_modules\ghost-ignition\lib\errors\index.js:75:23)
    at C:\Users\kirrg001\Desktop\dev\ghost\node_modules\passport-ghost\lib\oauth2.js:96:35
    at ClientRequest.<anonymous> (C:\Users\kirrg001\Desktop\dev\ghost\node_modules\oauth\lib\oauth2.js:148:5)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
```

This is pretty cool, it shows us lots of information except of the information where the error is coming from. Yeah you can read through the stack, but as a non Ghost developer, that might be confusing.
I would suggest adding an error code to the BadRequestError. Or an error help value.

**Comment by ErisDS** [comment]
This shouldn't be a fatal error for starting Ghost, IMO?

**Comment by kirrg001** [comment]
If you are using auth type `ghost` and you can't register your public client (because Ghost.org is down) and Ghost won't exit (!), then you would get problems when loading localhost in the browser. If there is no client registered, you can never successfully finish the Ghost setup. What do you suggest?

**Comment by ErisDS** [comment]
IMO, Ghost should always start. 
I realise, that trying to register a client is important, but it's not critical to starting Ghost? 

If I've already setup Ghost and have an active session, I shouldn't have any trouble starting Ghost.

If I've not yet setup Ghost, the error should come when I try to authenticate, and it ought to tell me to try again later?

**Comment by kirrg001** [comment]
Closing.

Ghost does not exit anymore when the remote service can't be reached or a different error occurs.
I have optimised all kinds of error messages and added a retry hook, so Ghost more visibility on what is going on.

> If I've not yet setup Ghost, the error should come when I try to authenticate, and it ought to tell me to try again later?

Users can use the Ghost-CLI to look at the error log. (e.g. `ghost logs`)
If the remote service url is wrong or it's down, Ghost-Admin won't render the signin popup at all.

> If I've already setup Ghost and have an active session, I shouldn't have any trouble starting Ghost.

As Ghost doesn't exit anymore, user can proceed if something fails. Visibility is available via the server logs.

Please re-open if you have further concerns or use cases.
